name: CI

on:
  push:
    branches: 
      - dev

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-2019]

    steps:
    - name: checkout sources
      uses: actions/checkout@v1
      with:
        ref: dev
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.5'
        architecture: 'x86'
    - name: install deps
      run: python -m pip install -r requirements.txt
    - name: build release
      run: python setup.py build
